using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GiftShop.Data.Migrations
{
    public partial class AutoGeneratedIdAndSeed : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "ImageId",
                table: "Products",
                newName: "ImageUrl");

            migrationBuilder.InsertData(
                table: "ProductTypes",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { new Guid("1e1ee133-0f1a-4585-89ed-e251dd84b98d"), "Accessories" },
                    { new Guid("979b887d-03fc-4f43-91b4-1c36daae5ac5"), "Toys" },
                    { new Guid("c1143e77-ccfa-4231-bd25-49e29470f13a"), "Clothes" }
                });

            migrationBuilder.InsertData(
                table: "YarnTypes",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { new Guid("33db593a-7a2b-493d-ae3c-f35086510855"), "Alize Puffy" },
                    { new Guid("d9ff2381-dcad-4a99-b2f7-2c8a34af34b2"), "Alexander Yarn Ira" },
                    { new Guid("fa6e1ffc-2094-4b9d-a985-305443b7ef27"), "Baby Bunny" }
                });

            migrationBuilder.InsertData(
                table: "Products",
                columns: new[] { "Id", "Description", "ImageUrl", "Name", "OrderId", "Price", "ProductTypeId", "Quantity", "Size", "YarnTypeId" },
                values: new object[] { new Guid("4e0d8c44-eb7a-414c-83ab-fb7889e1ba72"), "A buquet of 5 roses", "https://res.cloudinary.com/andysgiftshop/image/upload/v1690300910/IMG_8323_axmhkr.jpg", "Roses", null, 20.00m, new Guid("1e1ee133-0f1a-4585-89ed-e251dd84b98d"), 2, "25 cm", new Guid("d9ff2381-dcad-4a99-b2f7-2c8a34af34b2") });

            migrationBuilder.InsertData(
                table: "Products",
                columns: new[] { "Id", "Description", "ImageUrl", "Name", "OrderId", "Price", "ProductTypeId", "Quantity", "Size", "YarnTypeId" },
                values: new object[] { new Guid("a356b9ee-4486-43d9-9b3e-f58490556376"), "Blue soft blanket", "https://res.cloudinary.com/andysgiftshop/image/upload/v1690300911/IMG_4014_yctppj.jpg", "Blanket", null, 130.00m, new Guid("1e1ee133-0f1a-4585-89ed-e251dd84b98d"), 1, "100x180 cm", new Guid("33db593a-7a2b-493d-ae3c-f35086510855") });

            migrationBuilder.InsertData(
                table: "Products",
                columns: new[] { "Id", "Description", "ImageUrl", "Name", "OrderId", "Price", "ProductTypeId", "Quantity", "Size", "YarnTypeId" },
                values: new object[] { new Guid("acd46b9f-131a-4c3b-8cdf-6a3c307d50f1"), "This baby dear is so adorable and a perfect Xmas gift.The scarf is with a custom color which should be added in the notes when you order :)", "https://res.cloudinary.com/andysgiftshop/image/upload/v1690300909/IMG_3999_qe9com.jpg", "Baby Dear", null, 25.00m, new Guid("979b887d-03fc-4f43-91b4-1c36daae5ac5"), 1, "20 cm", new Guid("fa6e1ffc-2094-4b9d-a985-305443b7ef27") });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "ProductTypes",
                keyColumn: "Id",
                keyValue: new Guid("c1143e77-ccfa-4231-bd25-49e29470f13a"));

            migrationBuilder.DeleteData(
                table: "Products",
                keyColumn: "Id",
                keyValue: new Guid("4e0d8c44-eb7a-414c-83ab-fb7889e1ba72"));

            migrationBuilder.DeleteData(
                table: "Products",
                keyColumn: "Id",
                keyValue: new Guid("a356b9ee-4486-43d9-9b3e-f58490556376"));

            migrationBuilder.DeleteData(
                table: "Products",
                keyColumn: "Id",
                keyValue: new Guid("acd46b9f-131a-4c3b-8cdf-6a3c307d50f1"));

            migrationBuilder.DeleteData(
                table: "ProductTypes",
                keyColumn: "Id",
                keyValue: new Guid("1e1ee133-0f1a-4585-89ed-e251dd84b98d"));

            migrationBuilder.DeleteData(
                table: "ProductTypes",
                keyColumn: "Id",
                keyValue: new Guid("979b887d-03fc-4f43-91b4-1c36daae5ac5"));

            migrationBuilder.DeleteData(
                table: "YarnTypes",
                keyColumn: "Id",
                keyValue: new Guid("33db593a-7a2b-493d-ae3c-f35086510855"));

            migrationBuilder.DeleteData(
                table: "YarnTypes",
                keyColumn: "Id",
                keyValue: new Guid("d9ff2381-dcad-4a99-b2f7-2c8a34af34b2"));

            migrationBuilder.DeleteData(
                table: "YarnTypes",
                keyColumn: "Id",
                keyValue: new Guid("fa6e1ffc-2094-4b9d-a985-305443b7ef27"));

            migrationBuilder.RenameColumn(
                name: "ImageUrl",
                table: "Products",
                newName: "ImageId");
        }
    }
}
